---
version: '3'

services:
  wakeonmc:
    image: ghcr.io/yannikmg/wakeonlan:latest
    container_name: wakeonmc
    network_mode: "host"
    environment:
      - BROADCAST=10.10.0.255
      - MACADDRESS=00:00:00:00:00:00
      - REDIRECTWEBPAGE=http://www.google.com/
      - PORT=3000
      - TIMETOREDIRECT=7
    restart: unless-stopped
    