---
version: '3'

services:
  wakeonmc:
    image: ghcr.io/yannikmg/wakeonlan:latest
    container_name: wakeonmc
    ports:
      - 3000:3000
    environment:
      - BROADCAST=10.10.0.255
      - MACADDRESS=00:00:00:00:00:00
      - REDIRECTWEBPAGE=http://www.google.com/
    restart: unless-stopped
    